# Generated by Django 4.2 on 2023-05-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='temp_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
