# Generated by Django 4.2 on 2023-05-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_project_temp_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='temp_text',
        ),
    ]
